#!/usr/bin/env bash

init() {
  # TODO
  export BW_SESSION="redacted"
}

query_entries() {
    mapfile -t files < <(bw list items --nointeraction --search "$1" | jq -r '.[].name')
}

open_entry() {
    username=$(bw get username --nointeraction "$1")
    password=$(bw get password --nointeraction "$1")
}
