
format = "$cmd_duration$hostname$directory$git_branch$git_commit$git_state$git_status$character"
#command_timeout = 5000

[git_branch]
symbol = ""

[cmd_duration]
format = "took [$duration]($style)\n"
min_time = 0

[hostname]
format = "[$hostname]($style):"
